---
- name: install package using when condition
  hosts: all
  tasks:
  - name: install apache on Redhat family
    yum:
      name: httpd
      state: latest
    when: ansible_facts['os_family'] == "RedHat"
  - name: install apache on ubuntu family
    yum: 
      name: apache2
      state: latest
    when: ansible_facts['os_family'] == "Debian"



