---
- name: install packages and start services
  hosts: ansible1
  tasks:
  - name: Install Packages
    yum:
      name:
      - vsftpd
      - httpd
      - samba
      state: latest
  - name: Enable services
    service: 
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
    - vsftpd
    - httpd
    - smb


