---
- name: simple block example
  hosts: all
  tasks:
  - name: settling up http
    block:
    - name: installing httpd
      yum:
        name: httpd
        state: present
    - name: restart httpd
      service:
        name: httpd
        state: started
    when: ansible_distribution == "Centos"
