---
- name: conditionals test
  hosts: all
  tasks:
  - name: update the kernel if sufficient space is avaliable in /boot
    package:
      name: kernel
      state: latest
    loop: "{{ ansible_facts['mounts'] }}"
    when: item.mount == "/boot" and item.size_available > 20000000    
